aliases:
  container_config: &container_config
    docker:
      - image: circleci/node:8
    working_directory: ~/react-native-dom
  
  restore_repo: &restore_repo
    restore_cache:
      keys:
        - rn-dom-repo-{{ .Branch }}-{{ .Revision }}
        - rn-dom-repo-{{ .Branch }}
        - rn-dom-repo
  
  npm_cache_key: &npm_cache_key
    v1-dependency-npm-{{ checksum "yarn.lock" }}

  npm_backup_cache_key: &npm_backup_cache_key
    v1-dependency-npm

  init_submodules: &init_submodules
    run:
      name: Initialize Submodules
      command: git submodule update --init

  restore_node_modules: &restore_node_modules
    restore_cache:
      keys:
        - *npm_cache_key
        - *npm_backup_cache_key
  
  rndom_cache_key: &rndom_cache_key
    rn-dom-lib-{{ .Branch }}-{{ .Revision }}
  
  restore_rndom: &restore_rndom
    restore_cache:
      keys:
        - *rndom_cache_key
  
  yoga_dom_cache_key: &yoga_dom_cache_key
    yoga-dom-{{ .Branch }}-{{ .Revision }}

  restore_yoga_dom: &restore_yoga_dom
    restore_cache:
      keys:
        - *yoga_dom_cache_key

  components_cache_key: &components_cache_key
    rndom-components-{{ .Branch }}-{{ .Revision }}

  restore_components: &restore_components
    restore_cache:
      keys:
        - *components_cache_key

  rntester_cache_key: &rntester_cache_key
    rntester-{{ .Branch }}-{{ .Revision }}

  restore_rntester: &restore_rntester
    restore_cache:
      keys:
        - *rntester_cache_key

  update_gcc: &update_gcc
    run:
      name: Update GCC
      command: |
        echo "deb http://ftp.us.debian.org/debian unstable main contrib non-free" > /etc/apt/sources.list.d/unstable.list
        apt-get update
        apt-get install --assume-yes -t unstable gcc-5 g++-5
        update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5
        gcc --version

version: 2
jobs:
  checkout_repo:
    <<: *container_config
    steps:
      # - *restore_repo
      # - *update_gcc
      - checkout
      - *init_submodules
      - run:
          name: Download Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: rn-dom-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - .
  
  unittest:
    <<: *container_config
    steps:
      - *restore_repo
      - run:
          name: Run Unittests
          command: yarn test
  
  build_react_native_dom:
    <<: *container_config
    steps:
      - *restore_repo
      - run:
          name: Build react-native-dom
          command: cd packages/react-native-dom && yarn compile
      - save_cache:
          key: *rndom_cache_key
          paths:
            - packages/react-native-dom/lib

  build_yoga_wasm:
    machine: true
    working_directory: ~/react-native-dom
    steps:
      - *restore_repo
      - run:
          name: Build yoga-dom wasm
          command: cd packages/yoga-dom && ./build.sh
      - save_cache:
          key: yoga-wasm-{{ .Branch }}-{{ .Revision }}
          paths:
            - packages/yoga-dom/build

  build_yoga_dom:
    <<: *container_config
    steps:
      - *restore_repo
      - restore_cache:
         keys:
          - yoga-wasm-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Build yoga-dom
          command: cd packages/yoga-dom && yarn compile:bundle
      - save_cache:
          key: *yoga_dom_cache_key
          paths:
            - packages/yoga-dom/lib
  
  build_components:
    <<: *container_config
    steps:
      - *restore_repo
      - run:
          name: Build Custom Components
          command: yarn compile:components
      - save_cache:
          key: *components_cache_key
          paths:
            - packages/rndom-redbox/lib
            - packages/rndom-switch/lib

  build_rntester:
    <<: *container_config
    steps:
      - *restore_repo
      - *restore_rndom
      - *restore_yoga_dom
      - *restore_components
      - run:
          name: Build RNTester
          command: cd packages/react-native-dom && yarn build:rntester
      - save_cache:
          key: *rntester_cache_key
          paths:
            - ~/react-native-dom/packages/react-native-dom/dist
  
  deploy_rntester:
    <<: *container_config
    steps:
      - *restore_repo
      - *restore_rntester
      - run:
          name: Deploy RNTester to now.sh
          command: |
            sudo npm install -unsafe-perm --global now
            cd packages/react-native-dom/dist
            URL=$(now -t ${NOW_TOKEN})
            now alias -t ${NOW_TOKEN} ${URL} rntester.now.sh

workflows:
  version: 2
  build:
    jobs:
      - checkout_repo
      - unittest:
          requires:
            - checkout_repo
      - build_react_native_dom:
          requires:
            - checkout_repo
      - build_components:
          requires:
            - checkout_repo
      - build_yoga_wasm:
          requires:
            - checkout_repo
      - build_yoga_dom:
          requires:
            - build_yoga_wasm
      - build_rntester:
          requires:
            - build_components
            - build_react_native_dom
            - build_yoga_dom
            - unittest
      - deploy_rntester:
          requires:
            - build_rntester
          filters:
            branches:
              only:
                - master